using Newtonsoft.Json;
using TaxiManagerApp9000.DataAccess.Interfaces;
using TaxiManagerApp9000.Domain.Entities;

namespace TaxiManagerApp9000.DataAccess
{
    public class FileSystemDb<T> : IDb<T> where T : BaseEntity
    {
        private string _databaseFolder;
        private string _databasePath;
        private string _idPath;

        public FileSystemDb()
        {
            //We all know what happens here, it will generate files depending on what T is !!! T can be JUST 3 THINGS IN OUR CASE: User/Driver/Car
            _databaseFolder = "../../../Database";
            _databasePath = $"{_databaseFolder}/{typeof(T).Name}s.json";
            _idPath = $"{_databaseFolder}/{typeof(T).Name}Id.txt";

            if (!Directory.Exists(_databasePath))
            {
                Directory.CreateDirectory(_databaseFolder);
            }

            if (!File.Exists(_databasePath))
            {
                File.Create(_databasePath).Close();
            }

            if (!File.Exists(_idPath))
            {
                File.Create(_idPath).Close();
            }
        }

        public int Add(T entity) //this adds an entity to the db, depending on what type is it, what can it be ? It can be User/Driver/Car
        {
            List<T> data = new List<T>();
            using (StreamReader sr = new StreamReader(_databasePath))
            {
                data = JsonConvert.DeserializeObject<List<T>>(sr.ReadToEnd());
            }

            if (data == null)
            {
                data = new List<T>();
            }

            entity.Id = GenerateId(); //here it generates the new id, if the last id is 5, it will be autogenerated to be 6
            data.Add(entity); // here we add the new entity to the rest of the entities
            WriteData(data); // we just write them back to the json file

            return entity.Id;
        }

        public List<T> GetAll() // this gets all the entities
        {
            using (StreamReader sr = new StreamReader(_databasePath))
            {
                return JsonConvert.DeserializeObject<List<T>>(sr.ReadToEnd());
            }
        }

        public T GetById(int id) // this gets one entity by id
        {
            using (StreamReader sr = new StreamReader(_databasePath))
            {
                return JsonConvert.DeserializeObject<List<T>>(sr.ReadToEnd()).FirstOrDefault(x => x.Id == id);
            }
        }

        public bool RemoveById(int id) //This removes by id from the db, for all 3 entitites
        {
            List<T> data = new List<T>();
            using (StreamReader sr = new StreamReader(_databasePath))
            {
                data = JsonConvert.DeserializeObject<List<T>>(sr.ReadToEnd());
            }

            if (data == null)
            {
                data = new List<T>();
            }

            T item = data.SingleOrDefault(x => x.Id == id);

            if (item != null)
            {
                data.Remove(item);
                WriteData(data);
            }

            return true;

        }

        public bool Update(T entity) //This updates the current entity Car/Driver/User
        {
            List<T> data = new List<T>();
            using (StreamReader sr = new StreamReader(_databasePath))
            {
                data = JsonConvert.DeserializeObject<List<T>>(sr.ReadToEnd());
            }

            if (data == null)
            {
                data = new List<T>();
            }

            T item = data.SingleOrDefault(x => x.Id == entity.Id);

            if (item != null)
            {
                data[data.IndexOf(item)] = entity;
                WriteData(data);
            }

            return true;
        }

        private void WriteData(List<T> data) //this just writes all the data back to the DB/to the file
        {
            using (StreamWriter sw = new StreamWriter(_databasePath))
            {
                sw.WriteLine(JsonConvert.SerializeObject(data, Formatting.Indented));
            }
        }

        private int GenerateId() //this method takes the last Id that has been inserted in the DB, what id ? The id of the Car/User/Driver, depending on what T is. It takes it and add +1 to it.
        {
            int id = 1;
            using (StreamReader sr = new StreamReader(_idPath))
            {
                string currentId = sr.ReadLine();
                if (currentId != null)
                {
                    id = int.Parse(currentId);
                }
            }

            using (StreamWriter sw = new StreamWriter(_idPath))
            {
                sw.WriteLine(id + 1);
            }

            return id;
        }
    }
}
